function headertext = define_fluxall_headers()
% DEFINE_FLUXALL_HEADERS - returns column headers (variable names and units) for
%   UNM fluxall files
    
    headertext = {'year', 'year'; ...
                  'month', 'month'; ...
                  'day', 'day'; ...
                  'hour', 'hour'; ...
                  'min', 'minutes';...
                  'second', 'seconds'; ...
                  'date', 'character'; ...
                  'jday', 'day of year'; ...
                  'iok', 'flag'; ...
                  'u_mean', 'm/s'; ...
                  'v_mean', 'm/s'; ...
                  'w_mean', 'm/s'; ...
                  'temp_mean', 'K'; ...
                  'tdry', 'K'; ...
                  'wind_direction_theta', 'degrees'; ...
                  'speed', 'm/s'; ...
                  'rH', 'percent'; ...
                  'along_wind_velocity_variance', 'm^2/s^2'; ...
                  'cross_wind_velocity_variance', 'm^2/s^2'; ...
                  'vertical_wind_velocity_variance', 'm^2/s^2'; ...
                  'sonic_temperature_variance', 'K^2'; ...
                  'uw_co_variance', 'm^2/s^2'; ...
                  'vw_co_variance', 'm^2/s^2'; ...
                  'uv_co_variance', 'm^2/s^2'; ...
                  'ut_co_variance', 'm^2 K^2'; ...
                  'vt_co_variance', 'm^2 K^2'; ...
                  'wt_co_variance', 'm^2 K^2'; ...
                  'ustar_friction_velocity', 'm/s'; ...
                  'CO2_min', 'umol/mol dry air'; ...
                  'CO2_max', 'umol/mol dry air'; ...
                  'CO2_median', 'umol/mol dry air'; ...
                  'CO2_mean', 'umol/mol dry air'; ...
                  'CO2_std', 'umol/mol dry air'; ...
                  'H2O_min', 'mmol/mol dry air'; ...
                  'H2O_max', 'mmol/mol dry air'; ...
                  'H2O_median', 'mmol/mol dry air'; ...
                  'H2O_mean', 'mmol/mol dry air'; ...
                  'H2O_std', 'mmol/mol dry air'; ...
                  'Fc_raw', 'umol/m^2/s'; ...
                  'Fc_raw_massman', 'umol/m^2/s'; ...
                  'Fc_water_term', 'umol/m^2/s'; ...
                  'Fc_heat_term_massman', 'umol/m^2/s'; ...
                  'Fc_raw_massman_ourwpl', 'umol/m^2/s'; ...
                  'E_raw', ''; ...
                  'E_water_term', ''; ...
                  'E_heat_term_massman', ''; ...
                  'E_raw_massman', ''; ...
                  'E_rhov_massman', ''; ...
                  'SensibleHeat_dry', 'W m-2'; ...
                  'SensibleHeat_wet', 'W m-2)'; ...
                  'SensibleHeat_wetwet', 'W m-2'; ...
                  'HSdry_massman', ''; ...
                  'LatentHeat_raw', 'W m-2'; ...
                  'LatentHeat_raw_massman', 'W m-2'; ...
                  'LatentHeat_wpl_massman', 'W m-2'; ...
                  'rhoa_dry_air_molar_density', 'g/m^3 moist air'; ...
                  'rhov_dry_air_molar_density', 'g/m^3 moist air'; ...
                  'rhoc_dry_air_molar_density', 'g/m^3 moist air'; ...
                  'BouyancyFlux', ''; ...
                  'transport', '';...
                  'NaNs', ''; ...
                  'Maxs', ''; ...
                  'Mins', ''; ...
                  'Spikes', ''; ...
                  'Bad_variance', ''; ...
                  'zoL', ''; ...
                  'urot', ''; ...
                  'vrot', ''; ...
                  'wrot', ''; ...
                  'u_vector_u', ''; ...
                  'u_vector_v', ''; ...
                  'u_vector_w', ''};

