function fh = plot_siteyear_fingerprint_2x3array( sitecode, year )
% create 2/x array of fingerprint plots from gapfilled Ameriflux file for
% siteyear.  Plots Rg, RH, T, NEE, LE, H.
%   
% USAGE
%   fh = plot_siteyear_fingerprint_2x3array( sitecode, year )
%

this_data = parse_ameriflux_file( ...
    get_ameriflux_filename( int8( sitecode ), ...
                            year, ...
                            'gapfilled' ) );

h = RBD_plot_fingerprints( sitecode, year, ...
                           this_data.DTIME, ...
                           this_data.Rg, this_data.RH, this_data.TA, ...
                           this_data.FC, this_data.LE, this_data.H, ...
                           'ameriflux_6July_gapfilled' );
