sitecode = [ 1:4, 6, 10, 11 ];
years = { [ 2007: 2011 ], ...
          [ 2007:2011 ], ...
          [ 2007:2011 ], ...
          [ 2008:2011 ], ...
          [ 2007: 2011 ], ...
          [ 2010:2011 ], ...
          [ 2010:2011 ] };

GF_settings = { [ false false false ], ...
                [ false false false ], ...
                [ true true true ], ...
                [ false false false ], ...
                [ false false true ], ...
                [ false false true ], ...
                [ false false false ], ...
                [ false false true ] };

t0 = now();

%for i = 1:numel( sitecode )
for i = 1:1
    for j = 1:numel( years{ i } )
        fprintf( 'site: %d, year: %d\n', sitecode( i ), years{i}(j) );
        % UNM_RemoveBadData( sitecode( i ), years{i}(j), 'draw_plots', false);
        % UNM_fill_met_gaps_from_nearby_site( sitecode( i ), years{i}(j), ...
        %                                     false, GF_settings{i} );
        %UNM_Ameriflux_file_maker_TWH( sitecode( i ), years{i}(j) );
        plot_radiation_vs_solar_angle( sitecode( i ), years{i}(j) );
    end
end

minutes_per_day = 24.0 * 60.0;
delta_t = round( ( now() - t0 ) * minutes_per_day );
fprintf( 'done (%d minutes)\n', delta_t );
