% script to process 10 hz data to 30-minute average fluxes.

for this_site = [ 5, 6, 1, 2, 3, 4, 10, 11 ]
    try 
        result = ...
            UNM_process_10hz_main( this_site, ...
                                   datenum( 2012, 1, 1 ), ...
                                   now(), ...
                                   'rotation', ...
                                   sonic_rotation.threeD );
    catch err
        disp( getReport( err ) );
    end
end

% for year = 2009:2010
%     %for this_site = enumeration( 'UNM_sites' )
%     for this_site = 1:6
%             if ~( ( this_site == UNM_sites.PJ_girdle ) & ...
%                   ( year == 2009 ) )
%                 try 
%                     result = ...
%                         UNM_process_10hz_main( this_site, ...
%                                                datenum( year, 1, 1 ), ...
%                                                datenum( year, 12, 31, ...
%                                                         11, 59, 59), ...
%                                                'rotation', ...
%                                                sonic_rotation.threeD );
%                 catch err
%                     disp( getReport( err ) );
%                 end
%             end
%     end
% end