args = UNM_data_feeder('GLand', ...
		       'year_start', 2011, ...  
		       'cmon_start', 7, ...
		       'cday_start', 8, ...
		       'hour_start', 14, ...
		       'min_start', 27, ...
		       'year_end', 2011, ...
		       'cmon_end', 8, ...
		       'cday_end', 27);

infile_names = UNM_filebuilder(args.site, args.date_start, args.date_end);

%user_xls = UNM_data_feeder('GLand', 'input_from_excel', true); 

  % this snippet needs to go in a main caller function
% $$$     for i=1:n
% $$$         UNM_filebuilder(drive,figures,rotation,lag,writefluxall,site(i),year(i),f_jday(i),l_jday(i),starttime_num(i),dircode)
% $$$         pack
% $$$         i=i+1;
% $$$     end