args = UNM_data_feeder('PJ', ...
		       'year_start', 2011, ...  
		       'cmon_start', 8, ...
		       'cday_start', 1, ...
		       'hour_start', 00, ...
		       'min_start', 00, ...
		       'year_end', 2011, ...
		       'cmon_end', 8, ...
		       'cday_end', 27);
%args_xls = UNM_data_feeder('GLand', 'input_from_excel', true); 

[infile_names, all_dates] = UNM_filebuilder(args.site, args.date_start, args.date_end);

for i = 1:5
  UNM_data_processor(infile_names{i}, all_dates(i), args.site, args.figures, ...
		     args.rotation, args.lag_nsteps, args.writefluxall);
end
