args = UNM_data_feeder('PJ', ...
		       'year_start', 2011, ...  
		       'cmon_start', 8, ...
		       'cday_start', 1, ...
		       'hour_start', 00, ...
		       'min_start', 00, ...
		       'year_end', 2011, ...
		       'cmon_end', 8, ...
		       'cday_end', 27);
%args_xls = UNM_data_feeder('GLand', 'input_from_excel', true); 

infile_names = UNM_filebuilder(args.site, args.date_start, args.date_end);

UNM_data_processor(infile_names{1}, args.date_start, args.site, args.figures, ...
		   args.rotation, args.lag_nsteps, args.writefluxall);

% for i = 1:numel(infile_names)
%   UNM_data_processor(infile_names{i},	% 
