function outfile = UNM_online_gapfiller_submit_job(sitecode, year)
% UNM_ONLINE_GAPFILLER_SUBMIT_JOB - submit a gapfilling job to
%   MPI-biogeochemistry's online gapfilling and partitioning tool
%
% USAGE: outfile = UNM_online_gapfiller_submit_job(sitecode, year)
%
% (c) Timothy W. Hilton, UNM, Mar 2012

site_name = get_site_name( sitecode );
siteinfo = parse_UNM_site_table();
latitude = siteinfo.Latitude( sitecode );

processed_flux_dir = fullfile( 'C:', ...
                         'Research_Flux_Towers', ...
                         'Flux_Tower_Data_by_Site', ...
                         site_name, ...
                         'processed_flux' );

fluxall_file = sprintf( '%s_flux_all_%d_for_gap_filling.txt', ...
                        site_name, year );

outfile = sprintf( '%s_%s_%d_gapfiller_confirmation.html', ...
                   datestr( now(), 'yyyymmdd' ), site_name, year );

% change working directory to the processed_flux directory -- that way we
% don't have to deal with spaces in the path
orig_dir = pwd();
cd( processed_flux_dir );

% build a curl command to submit the form and submit the job
URL = 'http://www.bgc-jena.mpg.de/~MDIwork/eddyproc/submit.php';

cmd = sprintf( [ 'curl -F filename="@%s" ', ...
                 '-F year="%d" ', ...
                 '-F timefmt="6" ', ...
                 '-F Delimiter="," ', ...
                 '-F Unc="NO" ', ...
                 '-F ustarfilter="NO" ', ...
                 '-F FluxPart="YES" ', ...
                 '-F GL2010="YES" ', ...
                 '-F TempVar="Tair" ', ...
                 '-F Latitude="%f" ', ...
                 '--form-string email="hilton@unm.edu" ', ...
                 '%s > %s' ], ...
               fluxall_file, year, latitude, URL, outfile );
fprintf( 'command: %s\n', cmd );
system( cmd );

movefile( outfile, get_out_directory( sitecode ) );

% change working directory back to original directory
cd( orig_dir );
                 


