classdef UNM_sites_info
    
    properties
        
        GLand;
        SLand;
        JSav;
        PJ;
        PPine;
        MCon;
        TX;
        TX_grassland;
        TX_forest;
        PJ_girdle;
        New_GLand;
        SevEco;        
    end %properties
    
    methods
        
        function obj = UNM_sites_info( obj )
        % UNM_SITES_INFO - class constructor
        %   
        
        obj.GLand = struct( 'short_name', 'GLand',...                            
                            'long_name', 'Sevilleta burned grass', ...
                            'ameriflux', 'US-Seg', ...
                            'ORNL', 'ussevdeg', ...                            
                            'latitude', 34.3402, ...
                            'longitude', -106.68542, ...
                            'elevation', 1619 );
        
        obj.SLand = struct( 'short_name', 'SLand',...                            
                            'long_name', 'Sevilleta shrub', ...
                            'ameriflux', 'US-Ses', ...
                            'ORNL', 'ussevdes', ...                            
                            'latitude', 34.3338, ...
                            'longitude', -106.73401, ...
                            'elevation', 1608 );
        
        obj.JSav = struct( 'short_name', 'JSav',...                            
                           'long_name', 'Sevilleta juniper savanna', ...
                           'ameriflux', 'US-Wjs', ...
                           'ORNL', 'usjunsav', ...                            
                           'latitude', 34.425489, ...
                           'longitude', -105.861545, ...
                           'elevation', 1927 );
        
        obj.PJ = struct( 'short_name', 'PJ', ...                            
                            'long_name', 'pinon juniper control', ...
                            'ameriflux', 'US-Mpj', ...
                            'ORNL', 'uspinonj', ...                            
                            'latitude', 34.437, ... 
                            'longitude', -106.238, ...
                            'elevation', 2195 );
        
        obj.PPine = struct( 'short_name', 'PPine',...                            
                            'long_name', 'Ponderosa Pine', ...
                            'ameriflux', 'US-Vcp', ...
                            'ORNL', 'usvalpon', ...                            
                            'latitude', 35.86236, ...
                            'longitude', -106.59743, ...
                            'elevation', 2488 );

        obj.MCon = struct( 'short_name', 'MCon',...                            
                           'long_name', 'Valles Caldera Mixed Conifer', ...
                           'ameriflux', 'US-Vcm', ...
                           'ORNL', 'usvalcon', ...                            
                           'latitude', 35.888, ...
                           'longitude', -106.532, ...
                           'elevation', 3025 );
        
        obj.TX = struct( 'short_name', 'TX',...                            
                         'long_name', 'Freeman Ranch juniper savanna', ...
                         'ameriflux', 'US-FR2', ...
                         'ORNL', '', ...                            
                         'latitude', 29.94943333, ...
                         'longitude', -97.99611667, ...
                         'elevation', 264 );

        obj.TX = struct( 'short_name', 'TX_forest',...                            
                         'long_name', 'Freeman Ranch forest', ...
                         'ameriflux', 'US-FR3', ...
                         'ORNL', '', ...                            
                         'latitude', 29.94943333, ...
                         'longitude', -97.99611667, ...
                         'elevation', 264 );

        obj.TX = struct( 'short_name', 'TX_grass',...                            
                         'long_name', 'Freeman Ranch grassland', ...
                         'ameriflux', 'US-FR1', ...
                         'ORNL', '', ...                            
                         'latitude', 29.94943333, ...
                         'longitude', -97.99611667, ...
                         'elevation', 264 );

        obj.PJ_girdle = struct( 'short_name', 'PJ_girdle',...
                         'long_name', 'PJ manipulation', ...
                         'ameriflux', 'US-Mpg', ...
                         'ORNL', '', ...
                         'latitude', 34.437, ...
                         'longitude', -106.238, ...
                         'elevation', 2195 );
        
        obj.New_GLand = struct( 'short_name', 'New_GLand',...
                                'long_name', 'Sevilleta Unburned grassland', ...
                                'ameriflux', 'US-Sen', ...
                                'ORNL', '', ...
                                'latitude', 34.3402, ...
                                'longitude', -106.68542, ...
                                'elevation', 1619 );
        
        obj.SevEco = struct( 'short_name', 'Sev_Eco',...
                             'long_name', 'Sevilleta ecotone', ...
                             'ameriflux', '', ...
                             'ORNL', '', ...
                             'latitude', NaN, ...
                             'longitude', NaN, ...
                             'elevation', NaN );
        
        end
    end %methods
    end %classdef
        %--------------------------------------------------
