% script to combine, verify and fill timestamps, and reformat variable names
% for 2010 and 2011 burned grassland 30-minute datalogger files.

%% define file locations
path = fullfile( getenv('FLUXROOT','SiteData/GLand/toa5/';

files = ...
    { 'TOA5_GLand_2010_12_21_1600.DAT', ...
      'TOA5_GLand_2011_01_25_1300.dat', ...
      'TOA5_GLand_2011_02_08_1500.DAT', ...
      'TOA5_GLand_2011_03_10_1700.DAT', ...
      'TOA5_GLand_2011_04_14_1530.DAT', ...
      'TOA5_GLand_2011_05_24_1500.DAT', ...
      'TOA5_GLand_2011_06_09_1630.DAT', ...
      'TOA5_GLand_2011_07_27_0800.DAT', ...
      'TOA5_GLand_2011_07_27_1330.DAT', ...
      'TOA5_GLand_2011_08_18_1100.dat', ...
      'TOA5_GLand_2011_09_17_1600.dat' }';

fullpaths = strcat(cellstr( repmat( path, length( files ), 1) ), files);

%%--------------------
%% read 1 Jan to 25 May into one table
one = toa5_2_table( fullpaths{ 1 } );
for i = 2:6
    one = vertcat( one, toa5_2_table( fullpaths{ i } ) );
end
one.DUMMY = repmat( NaN, size( one, 1 ), 1 );

%% read 25 May to November into another table (with different var names)
two = toa5_2_table( fullpaths{ 7 } );
two.Properties.VariableNames = strrep( two.Properties.VariableNames, 'SWC', 'swc' );
for i = 8:length( files )
    tmp = toa5_2_table( fullpaths{ i } );
    tmp.Properties.VariableNames = strrep( tmp.Properties.VariableNames, 'SWC', 'swc' );
    two = vertcat( two, tmp );
end
two.DUMMY = repmat( NaN, size( two, 1 ), 1 );

%--------------------

% convert SWC from milliseconds to volumetric water content using quadratic
% conversion equation from CS616 and CS626 manual section 6.3 (p 29):
% VWC = -0.0663 - 0.0063*period + 0.0007*period^2
SWC_cols = regexp( two.Properties.VariableNames, ...
                   'swc_(open[12]|grass[12])_[0-9]' );
SWC_cols = find( ~cellfun( 'isempty', SWC_cols ) );
SWC = double( two( :, SWC_cols ) );
SWC = ( -0.0663 - ( 0.0063 * SWC ) + ( 0.0007 * ( SWC .^ 2 ) ) );

% Will need equivalent table function
two = replacedata( two, SWC, SWC_cols );



%%--------------------

% initialize result to the variables that exist both pre- and post- datalogger
% changes
[ common_vars, one_idx, two_idx ] = intersect( one.Properties.VariableNames, ...
                                               two.Properties.VariableNames );
result = vertcat( one( :, one_idx ), two( :, two_idx ) );
%among the headers common to both, preserve the order that appears in the
%pre-June data.  (The default is alphabetical order).
[ discard, col_idx ] = sort( one_idx );
result = result( :, col_idx );

% now match the variables whose names changed and add the new variables
col_header_map = { ...
    'par_Avg', 'par_face_down_Avg', 'par_face_down_Avg'; ...
    'par_lite_Avg', 'par_face_up_Avg', 'par_face_up_Avg'; ...
    'TCAV_grass_Avg', 'TCAV_grass_2_Avg', 'TCAV_grass_Avg'; ...
    'TCAV_open_Avg', 'TCAV_open_1_Avg', 'TCAV_open_Avg'; ...
    'Tsoil_avg', 'DUMMY', 'Tsoil_avg'; ...
    'del_Tsoil', 'del_Tsoil_1_', 'del_Tsoil'; ...
    'grass1_12p5cm', 'echo_grass1_12p5cm_Avg', 'echo_grass1_12p5cm_Avg'; ...
    'grass1_22p5cm', 'echo_grass1_22p5cm_Avg', 'echo_grass1_22p5cm_Avg'; ...
    'grass1_2p5cm', 'echo_grass1_2p5cm_Avg', 'echo_grass1_2p5cm_Avg'; ...
    'grass1_37p5cm', 'echo_grass1_37p5cm_Avg', 'echo_grass1_37p5cm_Avg'; ...
    'grass1_52p5cm', 'echo_grass1_52p5cm_Avg', 'echo_grass1_52p5cm_Avg'; ...
    'grass2_12p5cm', 'echo_grass2_12p5cm_Avg', 'echo_grass2_12p5cm_Avg'; ...
    'grass2_22p5cm', 'echo_grass2_22p5cm_Avg', 'echo_grass2_22p5cm_Avg'; ...
    'grass2_2p5cm', 'echo_grass2_2p5cm_Avg', 'echo_grass2_2p5cm_Avg'; ...
    'grass2_37p5cm', 'echo_grass2_37p5cm_Avg', 'echo_grass2_37p5cm_Avg'; ...
    'grass2_52p5cm', 'echo_grass2_52p5cm_Avg', 'echo_grass2_52p5cm_Avg'; ...
    'hfp01_grass_Avg', 'hfp_grass_1_Avg', 'hfp01_grass_Avg'; ...
    'hfp01_open_Avg', 'hfp_grass_2_Avg', 'hfp01_open_Avg'; ...
    'hft3_grass_Avg', 'hfp_open_1_Avg', 'hft3_grass_Avg'; ...
    'hft3_open_Avg', 'hfp_open_2_Avg', 'hft3_open_Avg'; ...
    'open1_12p5cm', 'swc_open1_12p5cm_Avg', 'open1_12p5cm'; ...
    'open1_22p5cm', 'swc_open1_22p5cm_Avg', 'open1_22p5cm'; ...
    'open1_2p5cm', 'swc_open1_2p5cm_Avg', 'open1_2p5cm'; ...
    'open1_37p5cm', 'swc_open1_37p5cm_Avg', 'open1_37p5cm'; ...
    'DUMMY', 'swc_open1_52p5cm_Avg', 'open1_52p5cm'; ...
    'open2_12p5cm', 'swc_open2_12p5cm_Avg', 'open2_12p5cm'; ...
    'open2_22p5cm', 'swc_open2_22p5cm_Avg', 'open2_22p5cm'; ...
    'open2_2p5cm', 'swc_open2_2p5cm_Avg', 'open2_2p5cm'; ...
    'open2_37p5cm', 'swc_open2_37p5cm_Avg', 'open2_37p5cm'; ...
    'DUMMY', 'swc_open2_52p5cm_Avg', 'open2_52p5cm'; ...
    'grass1_12p5cm', 'swc_grass1_12p5cm_Avg', 'grass1_12p5cm'; ...
    'grass1_22p5cm', 'swc_grass1_22p5cm_Avg', 'grass1_22p5cm'; ...
    'grass1_2p5cm', 'swc_grass1_2p5cm_Avg', 'grass1_2p5cm'; ...
    'grass1_37p5cm', 'swc_grass1_37p5cm_Avg', 'grass1_37p5cm'; ...
    'grass1_52p5cm', 'swc_grass1_52p5cm_Avg', 'grass1_52p5cm'; ...
    'grass2_12p5cm', 'swc_grass2_12p5cm_Avg', 'grass2_12p5cm'; ...
    'grass2_22p5cm', 'swc_grass2_22p5cm_Avg', 'grass2_22p5cm'; ...
    'grass2_2p5cm', 'swc_grass2_2p5cm_Avg', 'grass2_2p5cm'; ...
    'grass2_37p5cm', 'swc_grass2_37p5cm_Avg', 'grass2_37p5cm'; ...
    'grass2_52p5cm', 'swc_grass2_52p5cm_Avg', 'grass2_52p5cm'; ...
    'DUMMY', 'soil_co2_grass_1_10cm_Avg', 'soil_co2_grass_1_10cm_Avg'; ...
    'DUMMY', 'soil_co2_grass_1_20cm_Avg', 'soil_co2_grass_1_20cm_Avg'; ...
    'DUMMY', 'soil_co2_grass_1_50cm_Avg', 'soil_co2_grass_1_50cm_Avg'; ...
    'DUMMY', 'soil_co2_grass_1_20cm_Avg', 'soil_co2_grass_1_20cm_Avg'; ...
    'DUMMY', 'soil_co2_grass_1_50cm_Avg', 'soil_co2_grass_1_50cm_Avg'; ...
    'DUMMY', 'soil_co2_grass_1_5cm_Avg', 'soil_co2_grass_1_5cm_Avg'; ...
    'DUMMY', 'soil_co2_grass_2_10cm_Avg', 'soil_co2_grass_2_10cm_Avg'; ...
    'DUMMY', 'soil_co2_grass_2_20cm_Avg', 'soil_co2_grass_2_20cm_Avg'; ...
    'DUMMY', 'soil_co2_grass_2_50cm_Avg', 'soil_co2_grass_2_50cm_Avg'; ...
    'DUMMY', 'soil_co2_grass_2_5cm_Avg', 'soil_co2_grass_2_5cm_Avg'; ...
    'DUMMY', 'soil_co2_grass_3_10cm_Avg', 'soil_co2_grass_3_10cm_Avg'; ...
    'DUMMY', 'soil_co2_grass_3_20cm_Avg', 'soil_co2_grass_3_20cm_Avg'; ...
    'DUMMY', 'soil_co2_grass_3_50cm_Avg', 'soil_co2_grass_3_50cm_Avg'; ...
    'DUMMY', 'soil_co2_grass_3_5cm_Avg', 'soil_co2_grass_3_5cm_Avg'; ...
    'DUMMY', 'mux_soil_wcr_Avg_17_', 'mux_soil_wcr_Avg_17_'; ...
    'DUMMY', 'mux_soil_wcr_Avg_18_', 'mux_soil_wcr_Avg_18_'; ...
    'DUMMY', 'mux_soil_wcr_Avg_19_', 'mux_soil_wcr_Avg_19_'; ...
    'DUMMY', 'mux_soil_wcr_Avg_1_', 'mux_soil_wcr_Avg_1_'; ...
    'DUMMY', 'mux_soil_wcr_Avg_20_', 'mux_soil_wcr_Avg_20_'; ...
    'DUMMY', 'mux_soil_wcr_Avg_2_', 'mux_soil_wcr_Avg_2_'; ...
    'DUMMY', 'mux_soil_wcr_Avg_3_', 'mux_soil_wcr_Avg_3_'; ...
    'DUMMY', 'mux_soil_wcr_Avg_4_', 'mux_soil_wcr_Avg_4_'; ...
    'DUMMY', 'mux_soil_wcr_Avg_5_', 'mux_soil_wcr_Avg_5_'; ...
    'DUMMY', 'mux_soil_wcr_Avg_6_', 'mux_soil_wcr_Avg_6_'; ...
    'DUMMY', 'mux_soil_wcr_Avg_7_', 'mux_soil_wcr_Avg_7_'; ...
    'DUMMY', 'mux_soil_wcr_Avg_8_', 'mux_soil_wcr_Avg_8_'; ...
    'DUMMY', 'mux_soil_wcr_Avg_9_', 'mux_soil_wcr_Avg_9_'; };

% create new variables in result by concatentating pre-June data from
% column_header_map( :, 1 ) to post-June data from column_header_map( : ,2 ).
% The column header in result comes from column_header_map( :, 3 )
for i = 1:size( col_header_map, 1 )
    result.( col_header_map{ i, 3 } ) = ...
        vertcat( one.( col_header_map{ i, 1 } ), ...
                 two.( col_header_map{ i, 2 } ) );
end
    
%--------------------

% fill in any missing timestamps and write the combined data to disk
thirty_mins = 1 / 48;
result = table_fill_timestamps( result, 'TIMESTAMP',  thirty_mins );

% export( result, ...
%         'FILE', ...
%         fullfile( getenv( 'HOME' ), 'GLand_TOA_2011_combined.txt' ) );
