javaaddpath(['C:\cygwin\home\Tim\Software\ganymed-ssh2-build251beta1\' ...
             'ganymed-ssh2-build251beta1.jar']);

addpath('C:\cygwin\home\Tim\Software\sshfrommatlab');

sftpfrommatlab('jdelong', 'edacdata1.unm.edu', 'litvakdata', ...
               fullfile('C:', 'Research_Flux_Towers',...
                        'Flux_Tower_Data_by_Site', 'PJ_girdle',...
                        'Rawdata from cardd', 'Raw Data 2011', ...
                        'PJ_girdle_09-17-11.7z'), ...
               '/data/epscor/private/data/Upland_node/PJ_girdle/raw/PJ_girdle_09-17-11.7z');