% script to combine, verify and fill timestamps, and reformat variable names
% for 2010 and 2011 unburned grassland 30-minute datalogger files.

%% define file locations
path = fullfile( getenv('FLUXROOT','SiteData/New_GLand/toa5/';

files = ...
    { 'TOA5_New_Gland_2010_12_21_1630.dat', ...
      'TOA5_New_GLand_2011_01_25_1330.DAT', ...
      'TOA5_New_GLand_2011_02_08_1400.DAT', ...
      'TOA5_New_GLand_2011_02_23_1230.DAT', ...
      'TOA5_New_GLand_2011_03_10_1800.DAT', ...
      'TOA5_New_GLand_2011_03_23_1630.DAT', ...
      'TOA5_New_GLand_2011_04_13_1800.DAT', ...
      'TOA5_New_GLand_2011_06_23_1530.DAT', ...
      'TOA5_New_GLand_2011_07_27_1400.DAT', ...
      'TOA5_New_GLand_2011_08_18_1200.dat', ...
      'TOA5_New_GLand_2011_09_17_1700.dat' };

fullpaths = strcat(cellstr( repmat( path, length( files ), 1) ), files');

%%--------------------
%% read 1 Jan to 25 May into one table
one = toa5_2_table( fullpaths{ 1 } );
for i = 2:7
    one = vertcat( one, toa5_2_table( fullpaths{ i } ) );
end
one.DUMMY = repmat( NaN, size( one, 1 ), 1 );

%% read 25 May to November into another table (with different var names)
two = toa5_2_table( fullpaths{ 8 } );
two.Properties.VariableNames = strrep( two.Properties.VariableNames, 'SWC', 'swc' );
for i = 9:length( files )
    tmp = toa5_2_table( fullpaths{ i } );
    tmp.Properties.VariableNames = strrep( tmp.Properties.VariableNames, 'SWC', 'swc' );
    two = vertcat( two, tmp );
end
two.DUMMY = repmat( NaN, size( two, 1 ), 1 );

%%--------------------

% initialize result to the variables that exist both pre- and post- datalogger
% changes
[ common_vars, one_idx, two_idx ] = intersect( one.Properties.VariableNames, ...
                                               two.Properties.VariableNames );

result = vertcat( one( :, one_idx ), two( :, two_idx ) );
%among the headers common to both, preserve the order that appears in the
%pre-June data.  (The default is alphabetical order).
[ discard, col_idx ] = sort( one_idx );
result = result( :, col_idx );

% now match the variables whose names changed and add the new variables
col_header_map = { ...
    'TCAV_Avg', 'DUMMY', 'TCAV_Avg'; ...
    'par_Avg_1_', 'par_incoming_Avg', 'par_incoming_Avg'; ...
    'par_Avg_2_', 'par_upwelling_Avg', 'par_upwelling_Avg'; ...
    'DUMMY', 'TCAV_grass_Avg', 'TCAV_grass_Avg'; ...
    'DUMMY', 'TCAV_open_Avg', 'TCAV_open_Avg'; ...
    'DUMMY', 'soil_co2_g1_10cm_Avg', 'soil_co2_g1_10cm_Avg'; ...
    'DUMMY', 'soil_co2_g1_20cm_Avg', 'soil_co2_g1_20cm_Avg'; ...
    'DUMMY', 'soil_co2_g1_50cm_Avg', 'soil_co2_g1_50cm_Avg'; ...
    'DUMMY', 'soil_co2_g1_5cm_Avg', 'soil_co2_g1_5cm_Avg'; ...
    'DUMMY', 'soil_co2_g2_10cm_Avg', 'soil_co2_g2_10cm_Avg'; ...
    'DUMMY', 'soil_co2_g2_20cm_Avg', 'soil_co2_g2_20cm_Avg'; ...
    'DUMMY', 'soil_co2_g2_50cm_Avg', 'soil_co2_g2_50cm_Avg'; ...
    'DUMMY', 'soil_co2_g2_5cm_Avg', 'soil_co2_g2_5cm_Avg'; ...
    'DUMMY', 'soil_co2_g3_10cm_Avg', 'soil_co2_g3_10cm_Avg'; ...
    'DUMMY', 'soil_co2_g3_20cm_Avg', 'soil_co2_g3_20cm_Avg'; ...
    'DUMMY', 'soil_co2_g3_50cm_Avg', 'soil_co2_g3_50cm_Avg'; ...
    'DUMMY', 'soil_co2_g3_5cm_Avg', 'soil_co2_g3_5cm_Avg' };


% create new variables in result by concatentating pre-June data from
% column_header_map( :, 1 ) to post-June data from column_header_map( : ,2 ).
% The column header in result comes from column_header_map( :, 3 )
for i = 1:size( col_header_map, 1 )
    result.( col_header_map{ i, 3 } ) = ...
        vertcat( one.( col_header_map{ i, 1 } ), ...
                 two.( col_header_map{ i, 2 } ) );
end
    
%--------------------

% fill in any missing timestamps and write the combined data to disk
thirty_mins = 1 / 48;
result = table_fill_timestamps( result, 'TIMESTAMP',  thirty_mins );

year2011 = ( datenum( result.TIMESTAMP, 'mm/dd/yyyy HH:MM:SS' ) > ...
             datenum( 2010, 12, 31, 23, 59, 0 ) );
result = result( year2011, : );

export( result, ...
        'FILE', ...
        fullfile( getenv( 'HOME' ), 'New_GLand_TOA_2011_combined.txt' ) );

